---
- name: Install WireGuard
  apt:
    name: wireguard
    state: present
    update_cache: yes

- name: Copy client configuration
  copy:
    src: wg0.conf
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0600'

- name: Enable autostart WireGuard
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started