- name: Install dependencies
  apt:
    name:
      - curl
      - tar
    state: present
    update_cache: yes

- name: Fetch the latest Alertmanager release from GitHub API
  uri:
    url: "https://api.github.com/repos/prometheus/alertmanager/releases/latest"
    return_content: yes
  register: github_release

- name: Set Alertmanager version variable
  set_fact:
    alertmanager_version: "{{ github_release.json.tag_name | regex_replace('^v', '') }}"

- name: Display Alertmanager version
  debug:
    msg: "Latest Alertmanager version: {{ alertmanager_version }}"

- name: Create system user for Alertmanager
  user:
    name: alertmanager
    shell: /usr/sbin/nologin
    system: yes
    create_home: no

- name: Create Alertmanager directories
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
    mode: "0755"
  loop:
    - /etc/alertmanager
    - /var/lib/alertmanager
    - /opt/alertmanager

- name: Download Alertmanager {{ alertmanager_version }} from GitHub
  get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: /tmp/alertmanager.tar.gz
    mode: "0644"

- name: Extract Alertmanager archive
  unarchive:
    src: /tmp/alertmanager.tar.gz
    dest: /opt/
    remote_src: yes
    creates: "/opt/alertmanager-{{ alertmanager_version }}.linux-amd64"

- name: Install Alertmanager binaries to /usr/local/bin
  copy:
    src: "/opt/alertmanager-{{ alertmanager_version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: "0755"
    remote_src: yes
  loop:
    - alertmanager
    - amtool

- name: Copy Alertmanager configuration
  copy:
    dest: /etc/alertmanager/alertmanager.yml
    content: |
      global:
        resolve_timeout: 5m

      route:
        receiver: "default"
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 1h

      receivers:
        - name: "default"
          # add notification integrations here (email, telegram, webhook, etc.)

      inhibit_rules:
        - source_match:
            severity: "critical"
          target_match:
            severity: "warning"
          equal: ["alertname", "dev", "instance"]

    owner: alertmanager
    group: alertmanager
    mode: "0644"

- name: Create systemd unit for Alertmanager
  copy:
    dest: /etc/systemd/system/alertmanager.service
    content: |
      [Unit]
      Description=Prometheus Alertmanager
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=alertmanager
      Group=alertmanager
      Type=simple
      ExecStart=/usr/local/bin/alertmanager \
        --config.file=/etc/alertmanager/alertmanager.yml \
        --storage.path=/var/lib/alertmanager
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target

    mode: "0644"

- name: Reload systemd and enable Alertmanager
  systemd:
    daemon_reload: yes
    name: alertmanager
    state: started
    enabled: yes
